package com.dius.repository.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@DynamoDBTable(tableName = "Notification")
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Builder
@ToString
public class Notification {

    @Getter(onMethod = @__({@DynamoDBHashKey, @DynamoDBAutoGeneratedKey}))
    private String id;

    @Getter(onMethod = @__(@DynamoDBAttribute))
    private String title;

    @Getter(onMethod = @__(@DynamoDBAttribute))
    private String text;

}
